### ISSUE TITLE
请问缓存一行图像数据可以直接使用reg吗？

### ISSUE THREAD

**Issue by gnleaf** [becomequantum/Kryon#1]
比如：reg[7:0] linebuffer[2047:0];

**Comment by becomequantum** [comment]
貌似好像是可以的，俺没这样用过。这样可能会耗费大量的寄存器和FPGA逻辑，导致速度上不去。还有个关键问题是，用RAM可以同时有两个读写端口，这对图像处理至关重要。这个只用寄存器好像没法实现
